name = "user" # todo
main = "_worker.js"
compatibility_date = "2024-05-26"

[[routes]]
pattern = "user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "business.blibli.com.user.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.user.cepu.us.kg"
custom_domain = true

